### ISSUE TITLE
jackady quickstart fails on macOS M1 macbook air

### ISSUE THREAD

**Issue by autonome** [capyloon/nutria#11]
Cloned and ran `./jackady update-prebuilts` and got this:

<img width="624" alt="CleanShot 2022-02-21 at 15 05 41@2x" src="https://user-images.githubusercontent.com/50103/154970703-9da96d15-374b-4993-9b19-58f9ac514b36.png">

**Comment by fabricedesre** [comment]
We only have prebuilts for aarch64-apple-darwin - I wonder why you host is detected as x86_64...

**Comment by autonome** [comment]
ok searching around, found some hints that things that run under Rosetta can spit out that architecture. maybe something in the jackady build toolchain not updated?

**Comment by fabricedesre** [comment]
Can you run `rustup show` to see which target was inferred at install time by rustup?

About Rosetta, what's the value of using it when the native arch is supported? Worst case I should be able to also cross compile for `x86_64-apple-darwin`.

**Comment by autonome** [comment]
> Default host: x86_64-apple-darwin
> rustup home:  /Users/dietrich/.rustup
> 
> stable-x86_64-apple-darwin (default)
> rustc 1.58.1 (db9d1b20b 2022-01-20)

**Comment by autonome** [comment]
> About Rosetta, what's the value of using it when the native arch is supported? Worst case I should be able to also cross compile for x86_64-apple-darwin.

I figured there was some tool in the chain that was compiled pre-M1

**Comment by autonome** [comment]
https://github.com/rust-lang/rust/issues/73908

**Comment by fabricedesre** [comment]
Can you check if https://github.com/capyloon/nutria/commit/ed8dbcf343b3a9c89f7d17df217f7a6277a8605d fixes it for you?
