### ISSUE TITLE
No apps are available on amd64 install

### ISSUE THREAD

**Issue by suoko** [capyloon/nutria#24]
I installed the debian package and the system run but I can only open the camera app and go back to the homescreen.
How do I install / show apps ?

**Comment by fabricedesre** [comment]
You're likely still on the lock screen, from which you can just do a quick launch of the camera.
To unlock, swipe up the middle part (above the "chevron up" icon).

**Comment by suoko** [comment]
> You're likely still on the lock screen, from which you can just do a quick launch of the camera. To unlock, swipe up the middle part (above the "chevron up" icon).

I tried but nothing, no swipe occurs. Any keyboard shortcut to emulate it?

**Comment by fabricedesre** [comment]
No, there's no keyboard shortcut... Quite weird that a "2 fingers on the trackpad" swipe doesn't work...

**Comment by suoko** [comment]
> No, there's no keyboard shortcut... Quite weird that a "2 fingers on the trackpad" swipe doesn't work...

Gosh, you're right, that way it works. I was using the mouse wheel...
