### ISSUE TITLE
Improve the url-edit component 

### ISSUE THREAD

**Issue by fabricedesre** [capyloon/nutria#37]
This component: https://github.com/capyloon/nutria/blob/a66c441c51048bf3f52719143048b869c03724be/apps/system/components/url_edit.js is used when tapping on a page title either in the bottom status bar or in the site-info title. It has a few issues:
- Lack of favicons.
- Entering a search term doesn't work.

**Comment by mortcodesweb** [comment]
Favicons has been fixed. Now lemme try to do the search

**Comment by mortcodesweb** [comment]
search is kinda fixed for now. we just need to make it affected by the user's search settings

**Comment by fabricedesre** [comment]
Fixed by c45e722779f6475c70725220544d9275dc78ca89 and 443fe2df7034457511834b3efb8769e236d87c57
