### ISSUE TITLE
Inhibit Bitwarden Welcome page 

### ISSUE THREAD

**Issue by arky** [capyloon/nutria#4]
The default extensions are installed on first time launch of Nutria. When a user unlocks the screenlock they encounter Bitwarden welcome page. 

Perhaps it is a good idea to find a way to inhibit bitwarden 'Browser extension Installed' page 'https://bitwarden.com/browser-start/'

![image](https://user-images.githubusercontent.com/808895/152886827-5336047e-2736-495e-989b-d331d41e03f6.png)

https://github.com/bitwarden/browser/blob/bd770c90edd0c8b0fda93e7fa0ea13fbe326f611/src/background/runtime.background.ts#L217-L223

**Comment by fabricedesre** [comment]
A couple of remarks:
- This only happens at first run (or after a `./jackady clean`).
- We need proper web extension management, but it's not very high priority right now (help welcome!). Once that's ready we likely won't preload that extension.

**Comment by fabricedesre** [comment]
Done since 44fe34c removed bundled extensions, and moved them to opt in installation during the FTU in 6f29729
