### ISSUE TITLE
Running Desktop Build on WSL

### ISSUE THREAD

**Issue by aggggha** [capyloon/nutria#47]
Since GUI is supported on WSL, is it possible to run Nutria on WSL?
I was able to get the [required tools and prebuilt software](https://github.com/capyloon/nutria#quick-start) but I ended up in this situation (see the error on failed to connect to api daemon):

![Failed to connect to /tmp/api-daemon-socket : No such file or directory (os error 2)](https://user-images.githubusercontent.com/50284783/197401259-9ad6d97a-ee83-417a-85b3-79cdb9c74303.png)

And just showed a blank Capyloon window

**Comment by fabricedesre** [comment]
Hi! Interesting idea to run on WSL. I don't have a windows machine so I can't test on my side but let's try to debug what's going on.

In WSL can you check which sockets the api-daemon process is listening to? On linux something like `netstat -pln` works. Maybe the $TMP path is different in WSL, and we fail to connect because it's hardcoded in the configuration file.

**Comment by aggggha** [comment]
Okay so here's the capture of `netstat -pln`:

```
$ netstat -pln
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:6222          0.0.0.0:*               LISTEN      217/b2g
udp        0      0 127.0.0.1:323           0.0.0.0:*                           -
udp6       0      0 ::1:323                 :::*                                -
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     19472    -                    /run/WSL/1_interop
unix  2      [ ACC ]     STREAM     LISTENING     1045     -                    /run/WSL/1_interop
unix  2      [ ACC ]     STREAM     LISTENING     26630    -                    /run/WSL/8_interop
unix  2      [ ACC ]     STREAM     LISTENING     1180     -                    /run/WSL/328_interop
unix  2      [ ACC ]     STREAM     LISTENING     26710    -                    /var/run/dbus/system_bus_socket
unix  2      [ ACC ]     SEQPACKET  LISTENING     28683    -                    /mnt/wslg/weston-notify.sock
unix  2      [ ACC ]     STREAM     LISTENING     1051     -                    /mnt/wslg/runtime-dir/wayland-0
unix  2      [ ACC ]     STREAM     LISTENING     1052     -                    /tmp/.X11-unix/X0
unix  2      [ ACC ]     STREAM     LISTENING     19527    -                    /mnt/wslg/runtime-dir/pulse/native
unix  2      [ ACC ]     STREAM     LISTENING     19532    -                    /mnt/wslg/PulseServer
unix  2      [ ACC ]     STREAM     LISTENING     28739    -                    /mnt/wslg/PulseAudioRDPSource
unix  2      [ ACC ]     STREAM     LISTENING     19536    -                    /mnt/wslg/PulseAudioRDPSink
unix  2      [ ACC ]     STREAM     LISTENING     27666    224/dbus-daemon      @/tmp/dbus-rLlPSOB2Bc
unix  2      [ ACC ]     STREAM     LISTENING     1095     -                    @/tmp/dbus-i4yej20vGs
```

but i also found out that there's some kind of error (i'm not sure if it relate to this) still trying to fix this though. Something like ```/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found```. 

```
$ strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
...
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

I'll try to get back here when i got this problem solved

**Comment by fabricedesre** [comment]
The prebuilts are built on Ubuntu 22.04 LTS. Which distribution do you run under WSL?

**Comment by aggggha** [comment]
Maybe that's the problem. I'm running Ubuntu 20.04 LTS.

**Comment by fabricedesre** [comment]
Yes that's the issue, same thing happens when not running under WSL.

**Comment by aggggha** [comment]
Sweet! everything up and running. Closing this issue
