### ISSUE TITLE
Unlock swipe does not work (ubuntu)

### ISSUE THREAD

**Issue by friedger** [capyloon/nutria#51]
**Describe the bug**
The unlock swipe action is not recognized when running nutria. Clicking/pushing/swiping the chevron does not do anything.

** Environment **
- Desktop Linux
Ubuntu x64

**To Reproduce**
1. Type jackady dev
2. Try to swipe upwards
3. See error

**Expected behavior**
The screen should unlock.

**Comment by fabricedesre** [comment]
Ubuntu is also my dev environment, so I know for sure it can unlock :) I'm using either a 2 fingers swipe on my laptop trackpad, or the wheel on a usb mouse.

**Comment by friedger** [comment]
2 fingers! That worked. Thank you!
