### ISSUE TITLE
Disable Screen lock when the FTU is done

### ISSUE THREAD

**Issue by arky** [capyloon/nutria#66]
**Describe the bug**

Please disable lock screen when you launch nutria in 'desktop' mode 

** Environment **
- Desktop Linux

- Desktop Mac
- Device

**To Reproduce**
1. Run `./jackady dev --type desktop`
2. Click next or skip the onboarding
3. You will see the lock screen (see attached screenshot)

**Expected behavior**
You will see the main screen with apps

**Screenshots**
Lock Screen ![Screenshot from 2023-07-05 12-16-59](https://github.com/capyloon/nutria/assets/808895/757ddf00-5b76-4824-8438-54343e538335)

Main Screen ![Screenshot from 2023-07-05 12-20-49](https://github.com/capyloon/nutria/assets/808895/a835e289-c6bc-4880-8693-8ed3ffe0ec40)

**Additional context**
When you launch Capyloon on TV Media center interface you don't want users to first unlock the screen.

**Comment by arky** [comment]
@tylerchilds perhaps this good be one good feature to work on to improve the user experience in 10-foot UI

**Comment by fabricedesre** [comment]
In general (not just in desktop mode) we should disable the lock screen when we're done with the FTU (First Time Use) app run.

The relevant logic is in apps/system/js/bootstrap.js

**Comment by fabricedesre** [comment]
Fixed in https://github.com/capyloon/nutria/commit/6d4959378fa457cfc4b5b7c89693c652b1e7a1dd

**Comment by arky** [comment]
Thanks @fabricedesre for fixing this quickly.
