### ISSUE TITLE
Debian x86 32bit packages.

### ISSUE THREAD

**Issue by arky** [capyloon/nutria#70]
**Describe the bug**
Please kindly enable building debian packages x86 (32bit) machines. This would enable reusing older Eeepc machines for Capyloon desktop use.

**Comment by fabricedesre** [comment]
@arky do you have hardware to test on? I don't have any, so even if I manage to produce builds we need some way to smoke test these builds.

**Comment by arky** [comment]
I have multiple Eeepc or older laptops for testing with. 
 If you could just generate the x86 debian package and upload it to the repo. The I could make builds using my custom debos builds repo.

**Comment by arky** [comment]
@fabricedesre Could you guide me on how to add multiple arch to debian package generator. Thanks!

**Comment by arky** [comment]
x86 performance is not great, Closing this for now.
